//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rs007Control
{
    [Serializable]
    public class MagneMotionTray1Msg : Message
    {
        public const string k_RosMessageName = "rs007_control/MagneMotionTray1";
        public override string RosMessageName => k_RosMessageName;

        public int row;
        public int col;
        public int loaded;

        public MagneMotionTray1Msg()
        {
            this.row = 0;
            this.col = 0;
            this.loaded = 0;
        }

        public MagneMotionTray1Msg(int row, int col, int loaded)
        {
            this.row = row;
            this.col = col;
            this.loaded = loaded;
        }

        public static MagneMotionTray1Msg Deserialize(MessageDeserializer deserializer) => new MagneMotionTray1Msg(deserializer);

        private MagneMotionTray1Msg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.row);
            deserializer.Read(out this.col);
            deserializer.Read(out this.loaded);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.row);
            serializer.Write(this.col);
            serializer.Write(this.loaded);
        }

        public override string ToString()
        {
            return "MagneMotionTray1Msg: " +
            "\nrow: " + row.ToString() +
            "\ncol: " + col.ToString() +
            "\nloaded: " + loaded.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
