//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rs007Control
{
    [Serializable]
    public class MagneMotionSledMsg : Message
    {
        public const string k_RosMessageName = "rs007_control/MagneMotionSled";
        public override string RosMessageName => k_RosMessageName;

        public int loaded;
        public double position;
        public int pathid;
        public int cardit;

        public MagneMotionSledMsg()
        {
            this.loaded = 0;
            this.position = 0.0;
            this.pathid = 0;
            this.cardit = 0;
        }

        public MagneMotionSledMsg(int loaded, double position, int pathid, int cardit)
        {
            this.loaded = loaded;
            this.position = position;
            this.pathid = pathid;
            this.cardit = cardit;
        }

        public static MagneMotionSledMsg Deserialize(MessageDeserializer deserializer) => new MagneMotionSledMsg(deserializer);

        private MagneMotionSledMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.loaded);
            deserializer.Read(out this.position);
            deserializer.Read(out this.pathid);
            deserializer.Read(out this.cardit);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.loaded);
            serializer.Write(this.position);
            serializer.Write(this.pathid);
            serializer.Write(this.cardit);
        }

        public override string ToString()
        {
            return "MagneMotionSledMsg: " +
            "\nloaded: " + loaded.ToString() +
            "\nposition: " + position.ToString() +
            "\npathid: " + pathid.ToString() +
            "\ncardit: " + cardit.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
