//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rs007Control
{
    [Serializable]
    public class MagneMotionTrayMsg : Message
    {
        public const string k_RosMessageName = "rs007_control/MagneMotionTray";
        public override string RosMessageName => k_RosMessageName;

        public int[] loaded;

        public MagneMotionTrayMsg()
        {
            this.loaded = new int[12];
        }

        public MagneMotionTrayMsg(int[] loaded)
        {
            this.loaded = loaded;
        }

        public static MagneMotionTrayMsg Deserialize(MessageDeserializer deserializer) => new MagneMotionTrayMsg(deserializer);

        private MagneMotionTrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.loaded, sizeof(int), 12);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.loaded);
        }

        public override string ToString()
        {
            return "MagneMotionTrayMsg: " +
            "\nloaded: " + System.String.Join(", ", loaded.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
