//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rs007Control
{
    [Serializable]
    public class Rs007MoveitJointsSeqMsg : Message
    {
        public const string k_RosMessageName = "rs007_control/Rs007MoveitJointsSeq";
        public override string RosMessageName => k_RosMessageName;

        public double[] joints;
        public Geometry.PoseMsg[] poses;

        public Rs007MoveitJointsSeqMsg()
        {
            this.joints = new double[6];
            this.poses = new Geometry.PoseMsg[0];
        }

        public Rs007MoveitJointsSeqMsg(double[] joints, Geometry.PoseMsg[] poses)
        {
            this.joints = joints;
            this.poses = poses;
        }

        public static Rs007MoveitJointsSeqMsg Deserialize(MessageDeserializer deserializer) => new Rs007MoveitJointsSeqMsg(deserializer);

        private Rs007MoveitJointsSeqMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, sizeof(double), 6);
            deserializer.Read(out this.poses, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
            serializer.WriteLength(this.poses);
            serializer.Write(this.poses);
        }

        public override string ToString()
        {
            return "Rs007MoveitJointsSeqMsg: " +
            "\njoints: " + System.String.Join(", ", joints.ToList()) +
            "\nposes: " + System.String.Join(", ", poses.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
