//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rs007Control
{
    [Serializable]
    public class Rs007Joints1Msg : Message
    {
        public const string k_RosMessageName = "rs007_control/Rs007Joints1";
        public override string RosMessageName => k_RosMessageName;

        public int idx;
        public double joint;

        public Rs007Joints1Msg()
        {
            this.idx = 0;
            this.joint = 0.0;
        }

        public Rs007Joints1Msg(int idx, double joint)
        {
            this.idx = idx;
            this.joint = joint;
        }

        public static Rs007Joints1Msg Deserialize(MessageDeserializer deserializer) => new Rs007Joints1Msg(deserializer);

        private Rs007Joints1Msg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.idx);
            deserializer.Read(out this.joint);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.idx);
            serializer.Write(this.joint);
        }

        public override string ToString()
        {
            return "Rs007Joints1Msg: " +
            "\nidx: " + idx.ToString() +
            "\njoint: " + joint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
